### ISSUE TITLE
Both 404's and 500's error message's not working through exception_handler gem correclty

### ISSUE THREAD

**Issue by toymachiner62** [richpeck/exception_handler#1]
I'm only seeing the error message: 

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

When hitting both a 404, or a 500 error.

Here's a stacktrace for my app. 

ActiveRecord::RecordNotFound (Couldn't find User with 'id'=12 [WHERE `users`.`account_id` = ?]):
  app/controllers/users_controller.rb:10:in `show'

Processing by ExceptionHandler::ExceptionController#show as HTML
  Parameters: {"id"=>"12"}
  Account Load (0.4ms)  SELECT  `accounts`.* FROM `accounts`  WHERE `accounts`.`subdomain` = 'ematoda'  ORDER BY `accounts`.`id` ASC LIMIT 1
  Rendered exception_handler/exception/show.html.erb within layouts/application (0.1ms)
   (0.5ms)  SELECT COUNT(*) FROM `roles` INNER JOIN `users_roles` ON `roles`.`id` = `users_roles`.`role_id` WHERE `users_roles`.`user_id` = 1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))
Completed 500 Internal Server Error in 104ms
Error during failsafe response: This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/cancan-1.6.10/lib/cancan/controller_additions.rb:261:in `block in check_authorization'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:440:in `instance_exec'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:440:in `block in make_lambda'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:231:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:231:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:229:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:229:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:229:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:229:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:166:in `block in halting'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:86:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/callbacks.rb:86:in `run_callbacks'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/notifications.rb:159:in `block in instrument'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/notifications.rb:159:in `instrument'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activerecord-4.1.0.rc1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/abstract_controller/base.rb:136:in `process'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionview-4.1.0.rc1/lib/action_view/rendering.rb:30:in `process'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal.rb:195:in `dispatch'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_controller/metal.rb:231:in `block in action'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/exception_handler-0.3.0/lib/exception_handler.rb:20:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/exception_handler-0.3.0/lib/exception_handler.rb:20:in `block (2 levels) in <class:Exceptions>'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:46:in `render_exception'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/railties-4.1.0.rc1/lib/rails/rack/logger.rb:38:in `call_app'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/railties-4.1.0.rc1/lib/rails/rack/logger.rb:20:in `block in call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/tagged_logging.rb:26:in `tagged'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/tagged_logging.rb:68:in `tagged'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/railties-4.1.0.rc1/lib/rails/rack/logger.rb:20:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/quiet_assets-1.0.2/lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/activesupport-4.1.0.rc1/lib/active_support/cache/strategy/local_cache.rb:87:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/actionpack-4.1.0.rc1/lib/action_dispatch/middleware/static.rb:64:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/railties-4.1.0.rc1/lib/rails/engine.rb:515:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/railties-4.1.0.rc1/lib/rails/application.rb:142:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/puma-2.7.1/lib/puma/server.rb:486:in `handle_request'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/puma-2.7.1/lib/puma/server.rb:357:in `process_client'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/puma-2.7.1/lib/puma/server.rb:250:in `block in run'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `call'
  /Users/tomcaflisch/.rvm/gems/ruby-2.1.1@trakd/gems/puma-2.7.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

**Comment by awkale** [comment]
I just installed this gem and I'm using Devise but getting the original error. I'm not seeing the custom 400/500 error pages. 

Just the following:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

Was there another step to working with devise?

**Comment by richpeck** [comment]
Hi Alex,

Merci pour ton utiliser de la gem, je suis désolée it's causing issues.

---

The error you got is invoked by Rails when there are no ways to determine the error to be shown. This error is *normally* caused by some sort of low-level issue (perhaps with the EH gem itself).

In order to fix the issue (it's quite common and something I'm working on) is to **post the console log for the erroneous request**. This should show the actual error Rails is having, allowing us to work on a fix.

---

In regards Devise - the current functionality takes devise users and adds them to the db if they're logged in. I need to expand this in the next version.

R

**Comment by moncada1991** [comment]
I have the same error, I'm not seeing the custom 400/500 error pages.

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```
