### ISSUE TITLE
Actions return wrong HTTP status code

### ISSUE THREAD

**Issue by andoq** [richpeck/exception_handler#10]
On Rails 4.1, when I use the gem, the rendered 404 page has a HTTP status code of 200.  The original status code should be preserved.

I think that the gem is trying to do the correct thing - in the controller, the line is:

`respond_with status: @status`

But this doesn't work in Rails 4.1 and earlier, the correct way would be:

`respond_with nil, status: @status` 

You need to pass the resources first.

However, I haven't submitted a pull request because with Rails 4.2 out, you probably need to move away from respond_with - it's been deprecated and move out into the responders gem.  Or use the responders gem.  Not sure which is best, I haven't dug into 4.2 yet.

**Comment by ponchik** [comment]
Ive changed the exception_controller show action
-- respond_with status: @status
++ render status: @status

and now its giving the right status code. Not sure if its the right way, but it worked for me!

**Comment by richpeck** [comment]
I think it's an issue wit the new version of Rails - I'll have a look at it thank you :)

**Comment by InkSpeck** [comment]
Confirmed. This fix works well. 

changed show controller action to 
```
render :status => @status
```

**Comment by mcmegavolt** [comment]
#13

**Comment by richpeck** [comment]
Thank you for taking the time to not only open the issue, but contribute a fix. I have now committed a revised version incorporating your fix!
