### ISSUE TITLE
the gem does not work for Rails 6+ when the email option is enabled

### ISSUE THREAD

**Issue by drkaleem** [richpeck/exception_handler#103]
Error during failsafe response: undefined method `parent_name' for gchitt::Application:Class
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/railtie.rb:209:in `method_missing'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/app/views/exception_handler/mailers/new_exception.erb:1:in `__usr_share_rvm_gems_ruby_______gems_exception_handler_________app_views_exception_handler_mailers_new_exception_erb__3687581017939819404_68000'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/base.rb:247:in `public_send'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/base.rb:247:in `_run'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:154:in `block in render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:205:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:345:in `instrument_render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/template.rb:152:in `render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:61:in `block (2 levels) in render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `block in instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:56:in `block in render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:71:in `block in render_with_layout'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `block in instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/template_renderer.rb:11:in `render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/rendering.rb:117:in `block in _render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/base.rb:273:in `in_rendering_context'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/rendering.rb:116:in `_render_template'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/rendering.rb:103:in `render_to_body'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:958:in `block in collect_responses_from_templates'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:955:in `each'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:955:in `each'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:955:in `map'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:955:in `collect_responses_from_templates'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:933:in `collect_responses'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:841:in `mail'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/app/mailers/exception_handler/exception_mailer.rb:13:in `new_exception'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/base.rb:228:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actiontext-6.1.3/lib/action_text/rendering.rb:20:in `with_renderer'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actiontext-6.1.3/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:126:in `instance_exec'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/base.rb:165:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/rescuable.rb:25:in `block in process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/rescuable.rb:24:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/rendering.rb:39:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:615:in `block in process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `block in instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/base.rb:614:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
  <internal:kernel>:90:in `tap'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionmailer-6.1.3/lib/action_mailer/message_delivery.rb:30:in `__getobj__'
  /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:84:in `method_missing'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/app/models/exception_handler/exception.rb:93:in `block (2 levels) in <module:ExceptionHandler>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:427:in `instance_exec'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:427:in `block in make_lambda'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:516:in `block in invoke_after'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:516:in `each'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:516:in `invoke_after'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:107:in `run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:824:in `_run_initialize_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3/lib/active_record/core.rb:499:in `initialize'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/app/models/exception_handler/exception.rb:27:in `initialize'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3/lib/active_record/inheritance.rb:72:in `new'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3/lib/active_record/inheritance.rb:72:in `new'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/app/controllers/exception_handler/exceptions_controller.rb:20:in `block in <class:ExceptionsController>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:427:in `instance_exec'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:427:in `block in make_lambda'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:199:in `block in halting'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:512:in `block in invoke_before'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:512:in `each'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:512:in `invoke_before'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:115:in `block in run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actiontext-6.1.3/lib/action_text/rendering.rb:20:in `with_renderer'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actiontext-6.1.3/lib/action_text/engine.rb:55:in `block (4 levels) in <class:Engine>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:126:in `instance_exec'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `block in instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/notifications.rb:203:in `instrument'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/abstract_controller/base.rb:165:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionview-6.1.3/lib/action_view/rendering.rb:39:in `process'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal.rb:190:in `dispatch'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_controller/metal.rb:238:in `block in action'
  /usr/share/rvm/gems/ruby-3.0.0/gems/exception_handler-0.8.0.1/lib/exception_handler/engine.rb:54:in `block (2 levels) in <class:Engine>'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/show_exceptions.rb:52:in `render_exception'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/rack/logger.rb:37:in `call_app'
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/tagged_logging.rb:37:in `tagged'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/tagged_logging.rb:99:in `tagged'
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/rack/logger.rb:26:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/static.rb:24:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/middleware/host_authorization.rb:98:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/rack-mini-profiler-2.3.1/lib/mini_profiler/profiler.rb:373:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
  /usr/share/rvm/gems/ruby-3.0.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3/lib/rails/engine.rb:539:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/configuration.rb:247:in `call'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/request.rb:76:in `block in handle_request'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/thread_pool.rb:337:in `with_force_shutdown'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/request.rb:75:in `handle_request'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/server.rb:431:in `process_client'
  /usr/share/rvm/gems/ruby-3.0.0/gems/puma-5.2.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'

**Comment by drkaleem** [comment]
if I set the 

`exception_handler.email: nil`

then no issues, the error webpage shows up as expected.  But when it is changed to a valid email address like 

`exception_handler.email: "mealter@gmail.com"`

it fails altogether with the above exception stack. 

This issue appears like the already reported and resolved [here](https://github.com/richpeck/exception_handler/issues/100  )

**Comment by drkaleem** [comment]
FYI. the issue is with the use of Rails.application.class.parent_name class. Starting Rails 6 its now Rails.application.class.module_parent_name

**Comment by richpeck** [comment]
Was this not fixed with the recent push? I will check again if not

**Comment by drkaleem** [comment]
yes the recent push 0.8.0.1 did resolve it partially. 

as mentioned above, the gem works with rails 6 + using fix in 0.8.0.1. However the same gem fails with email option enabled. 

Thanks @richpeck  for looking into it

**Comment by drkaleem** [comment]
Any luck  ***@***.***> @richpeck/exception_handler on this bug. Thanks for your help.

**Comment by richpeck** [comment]
Looking at it now, apologies for the late reply, been extremely busy.

**Comment by richpeck** [comment]
This should have been fixed with `0.8.0.2`

**Comment by drkaleem** [comment]
Thank you it is now working well with 0.8.0.2.
