### ISSUE TITLE
eval in ExceptionHandler

### ISSUE THREAD

**Issue by yrashk** [richpeck/exception_handler#104]
https://github.com/richpeck/exception_handler/blob/e0e1e427fd2ac9226fec1c932dc20ac71d10066b/app/models/exception_handler/exception.rb#L29

Using `eval` is dangerous, and Rubocop highlights it, too.

For the purpose of the aforementioned line, wouldn't it be sufficient to do something like this?

```ruby
self[type] = type.constantize
```

Happy to submit a PR if necessary.

**Comment by richpeck** [comment]
It is dangerous, yes. 

I am not sure why I used it, but in this instance, it's just parsing a string, so I don't see it as a problem.

**Comment by yrashk** [comment]
Fair enough. Perhaps it is better to use `send` at least for performance reasons, while getting more safety, too?

Here's a back of the napkin test:

```ruby
require 'benchmark'

class TestEval
  def test
    hash = {}
    %i(message status).each do |type|
      hash[type] = eval type.to_s
    end
  end

  def message
    "Message"
  end

  def status
    "Status"
  end
end

class TestSend
  def test
    hash = {}
    %i(message status).each do |type|
      hash[type] = send(type)
    end
  end

  def message
    "Message"
  end

  def status
    "Status"
  end
end

test = TestEval.new
puts "eval: #{Benchmark.measure { test.test }}"

test = TestSend.new
puts "send: #{Benchmark.measure { test.test }}"
```

Result:

```
eval:   0.000013   0.000002   0.000015 (  0.000013)
send:   0.000002   0.000001   0.000003 (  0.000002)
```

About 6 times faster, and I am pretty sure it's a lot better with allocations!
