### ISSUE TITLE
json error message for api

### ISSUE THREAD

**Issue by coderawal** [richpeck/exception_handler#11]
when I make a json call to app it properly gives { "status":"404"} but no json message is displayed for 500 and other errors but gives "500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong." Any idea for returning proper json messages for 500 and errors and other, with details. I'm new to rails

**Comment by richpeck** [comment]
Are you using Rails 4.2.0+ ? `respond_with` was deprecated in this version, which is I think what is causing the issue. I'm getting back onto fixing this now

**Comment by coderawal** [comment]
Hi richpeck, thanks for response, I'm using rails 4.1

**Comment by richpeck** [comment]
Okay, can you take a screenshot of your error from the console? It will likely either be a dependency issue, or a core part of the code.

**Comment by coderawal** [comment]
![browser](https://cloud.githubusercontent.com/assets/7425858/5737836/87600c18-9c0d-11e4-89b6-8bd61ae56c4c.png)
![error](https://cloud.githubusercontent.com/assets/7425858/5737838/89487e52-9c0d-11e4-9667-f7cc75625e12.png)
![controller](https://cloud.githubusercontent.com/assets/7425858/5737879/e92a4986-9c0d-11e4-8b45-7bf5d3fb5dbc.png)

**Comment by richpeck** [comment]
Wow okay so we have a problem with titleize method in layouts/_list_header.erb or /layouts/devise.erb

I think this is a problem with Devise -- a way to see if this will work is to change the `select_layout` method to use use "application":

```def select_layout
    "application"
end```

If this works, it means the issue is with the gem's reliance on Devise, which I need to work around

**Comment by coderawal** [comment]
I figured out the problem, it was due to layouts and solved it. Thanks again, for helping richpeck.

**Comment by richpeck** [comment]
Nice! Was it an error on my part, or with your app?

**Comment by coderawal** [comment]
Actually it was an error on my app. Sorry!!
