### ISSUE TITLE
Wrong HTTP status

### ISSUE THREAD

**Issue by mcmegavolt** [richpeck/exception_handler#13]
I think you should use

```ruby
def show
  render status: @status
end
```
instead of
```ruby
respond_with status: @status
```
in your ``ExceptionController``

because now errors are generated with 200 HTTP status

My solution will fix this problem

**Comment by thehungrycoder** [comment]
It took me to understand a cause of a problem. I'm always getting 200 for a erroneous call and was so confused until I realized that it's `exception_handler` that actually sending 200 status. It should be fixed.

**Comment by richpeck** [comment]
@thehungrycoder Do you have a reference in the code for this? I'll fix the issue no problem

**Comment by thehungrycoder** [comment]
> @thehungrycoder Do you have a reference in the code for this? I'll fix the issue no problem

I think solution of @mcmegavolt will work. Currently I'm using another user's fork who implemented same thing and it's fine now.

**Comment by richpeck** [comment]
Okay bud, let me update it for you!!

**Comment by richpeck** [comment]
Fixed with latest commit.

**Comment by thehungrycoder** [comment]
@richpeck Sorry for late to reply. Thanks for fixing it. 
Another problem is it also intercepts non-html requests and doesn't return correct output. It returns html for json requests on exception.

**Comment by richpeck** [comment]
Okay let me see about this. I'm thinking a `respond_to` in the declarations of the controller class; I really need to implement a test suite into this as it has a user base now.

**Comment by thehungrycoder** [comment]
@richpeck 
Actually I think it's not a big issue now as long as it gives appropriate http error. Because if you return errors in `format`, there might be a question of how that error should be structured.
