### ISSUE TITLE
Cannot use gem with database

### ISSUE THREAD

**Issue by phlegx** [richpeck/exception_handler#17]
Hi!

I have done this steps:

```gem 'exception_handler', '~> 0.4'```

```$ bundle```
```$ rails g exception_handler:install```
```$ rails generate exception_handler:migration```
```$ rake db:migrate```

### Error 1

```
NoMethodError: undefined method `new' for ExceptionHandler:Module
active_record/migration.rb:774:in `load_migration'
```

#### Solution 1

Rename file ```20151110090613_exception_handler.rb``` to ```20151110090613_create_errors.rb``` or rename class name from *CreateErrors* to *ExceptionHandler*.

### Error 2

If I rename the migration from ```20151110090613_exception_handler.rb``` to ```20151110090613_create_errors.rb``` the Error 1 disappears but then I get another error.

```
== 20151110090613 CreateErrors: migrating =====================================
-- create_table(:errors)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "usables" does not exist
```

#### Solution 2

Change migration usable reference to

```ruby
t.references :usable, polymorphic: true
```

**Comment by richpeck** [comment]
We just received same error - working on a fix now.

**Comment by richpeck** [comment]
Confirm these fixed the problem, danke schoen!!
