### ISSUE TITLE
There's no documented way of hiding specific social media icons

### ISSUE THREAD

**Issue by jeanlescure** [richpeck/exception_handler#19]
We're using this gem in production and would like to have only **facebook** and **twitter**.

If you visit [http://www.thealigned.com/this-generates-an-error](http://www.thealigned.com/this-generates-an-error) you will see that other social icons are displayed and point to non-existing accounts.

Is there a way to turn off specific icons?

**Comment by richpeck** [comment]
Thanks for the email!

Sure, I just updated this in the latest release, although it looks like it still needs tweaking. I'll amend it tomorrow if you don't mind - I really need to sleep!

You can add the following to your `config/environments/production.rb` file:

config.exception_handler  {
   facebook: '.....',
   twitter: '.....'
}

This will change the icons in EH 0.4.6, but will not remove the others. I'm working on a way to get them to not show for you. The new version is heavily edited but that feature seemed to slip through!

Will report back in the morning if that's okay?

**Comment by richpeck** [comment]
Thanks for using ExceptionHandler too - it looks good in your app!

**Comment by jeanlescure** [comment]
Sounds great Rich,

Keep up the awesome work!

**Comment by richpeck** [comment]
Okay pushed a new version of the gem `0.4.7` with a fix:

![untitled](https://cloud.githubusercontent.com/assets/1104431/11607772/3a4e0882-9b4c-11e5-84ce-0c92c8a23182.png)

![untitled](https://cloud.githubusercontent.com/assets/1104431/11607773/4eae4760-9b4c-11e5-8a54-a99b91e6c3de.png)

You can do this by setting the `social` attributes in your `config` files (explained above). Putting `nil` in the various services you don't want to use will prevent them from showing.

Hope this helps,

Rich

**Comment by jeanlescure** [comment]
Wonderful! Thanks so much.

**Comment by richpeck** [comment]
No problem! Let me know if it fixes the issue - I'll close if so.

**Comment by jeanlescure** [comment]
Sorry, but issue is worse now, I can't get it to work at all, even after rolling back to previous config.

Here's the config I tried:

```ruby
    config.exception_handler = {
      db:     false, #-> defaults to :errors if true, else use :table_name
      email:  false, #-> need to integrate
      social: {
        :twitter  =>  'thealigned',
        :facebook   =>  'thealigned',
        :linkedin   =>  nil,
        :youtube  =>  nil,
        :fusion   =>  nil,
        :url => {
          :facebook   =>  'https://facebook.com',
          :twitter  =>  'http://twitter.com'
        },
      },
      layouts: {
        '400' => 'exception',
        '500' => 'exception'
      }
    }
```

And this is the original one:

```ruby
   config.exception_handler = {
      db:     false, #-> defaults to :errors if true, else use :table_name
      email:  false, #-> need to integrate
      social: {
          :twitter  =>  'thealigned',
          :facebook   =>  'thealigned',
          :linkedin   =>  'thealigned',
          :youtube  =>  'thealigned',
          :fusion   =>  'thealigned',
          :url => {
            :facebook   =>  'https://facebook.com',
            :twitter  =>  'http://twitter.com',
            :youtube  =>  'https://youtube.com/user',
            :linkedin   =>  'https://linkedin.com/company',
            :fusion   =>  'https://frontlinefusion.com',
        },
      },
      layouts: {
          '400' => 'exception',
          '500' => 'exception'
      }
    }
```

Here's a couple of screenshots in case they help:

<img width="562" alt="screen shot 2015-12-05 at 8 08 21 am" src="https://cloud.githubusercontent.com/assets/3330339/11608187/aec184e8-9b27-11e5-9e10-b6d07979e923.png">

<img width="571" alt="screen shot 2015-12-05 at 8 09 28 am" src="https://cloud.githubusercontent.com/assets/3330339/11608189/b4c6184a-9b27-11e5-95b4-bdf7929756f0.png">

**Comment by richpeck** [comment]
Let me try and recreate, thanks for posting your config

**Comment by richpeck** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1104431/11608331/4183a9a6-9b5e-11e5-88fb-089da4d5020e.png)

![untitled](https://cloud.githubusercontent.com/assets/1104431/11608333/529cd4d8-9b5e-11e5-89e8-769298f62660.png)

I just used your exact config with the latest version of ExceptionHandler (I had to update to 0.4.7) and it worked perfectly. BTW you don't need to define the `urls` for the social media services -- only if you want to change them should you change them, otherwise they resort to the defaults listed in the config.

--

Upon further inspection, I recognize the error. It's caused by the way we had to change the `config` handler -- instead of using a hash we now use a class. Thus, the controller *used* to call `ExceptionHandler.config[:social]`, now it has to call `ExceptionHandler.config.social`.

I think the errors are appearing here (`exception_controller.rb`):

![untitled](https://cloud.githubusercontent.com/assets/1104431/11608352/ade60936-9b5e-11e5-9546-ae4350c76f12.png)

Since it appears you've manually updated your controller, you'll have to change any reference to `ExcaptionHandler.config[:param]` to `ExceptionHandler.config.param` (in your case `ExceptionHandler.config.layout["400"]` etc.

**Comment by jeanlescure** [comment]
I had to delete all `exception_handler` folders (controller, models, helpers, views & assets), and the re-run `rails generate exception_handler:views`.

Now all works perfectly :)

Just in case, for future reference, here's the config I ended up using:

```ruby
    config.exception_handler = {
      db:     false, #-> defaults to :errors if true, else use :table_name
      email:  false, #-> need to integrate
      social: {
        :twitter  =>  'thealigned',
        :facebook   =>  'thealigned',
        :linkedin   =>  nil,
        :youtube  =>  nil,
        :fusion   =>  nil
      },
      layouts: {
          '400' => 'exception',
          '500' => 'exception'
      }
    }
```

Thanks again Rich!

**Comment by richpeck** [comment]
No problem sir, thank you!

You realize you can use the gem *without* putting the folders/files into your app, right? It's basically the same as Devise -- if you have 0 changes to any of the files, you can just leave them in the gem. If you want to change one, feel free to put it on your system.
