### ISSUE TITLE
How do you test this?

### ISSUE THREAD

**Issue by bf4** [richpeck/exception_handler#20]
I haven't been able to figure it out.

**Comment by richpeck** [comment]
What do you mean?

**Comment by bf4** [comment]
@richpeck thanks for the quick response.

We had a failure being raised from our exceptions app, so I went to see how you test this lib, and saw no tests, then I spent a lot of time source diving in Rails and googling and stacking-overflow and didn't really come to an acceptable solution... so, though I'd bring it up, to see if you've tested it elsewhere or know how

Example: request has invalid content type, exceptions app blows up, resulting in a failsafe error. I think I fixed the bug, but I can't test it.

**Comment by richpeck** [comment]
Caught me with my pants down sorry bud!! Haven't got round to a test suite for this yet; I really dislike testing and was hoping someone else would implement it. Poor excuse but it's been fine for me so far.

If you'd like me to implement a test suite when I update it for Rails 5, I'll happily do so. 

---

With the failsafe error, can you explain a little further? Haven't encountered this before!

Thanks for the message man, I just looked at your profile and.... wow! It's amazing someone of your caliber would be using the gem :)

**Comment by bf4** [comment]
So, I've since learned how to test something like this:

```ruby
  class TestExceptionController < ApplicationController
    use ActionDispatch::ShowExceptions, Rails.configuration.exceptions_app
    def index
      # something that raises an exception
    end
  end
```

then

```ruby
response = Rack::MockRequest.new(TestExceptionController.action(:index)).get('/', 'HTTP_ACCEPT' => 'application/json', 'action_dispatch.show_exceptions' => true)
```

**Comment by bf4** [comment]
@srghma 
> , can you provide more info
are you asking for help with your problem?

**Comment by richpeck** [comment]
Working on this now
