### ISSUE TITLE
Missing Rails 4.2+ dependency

### ISSUE THREAD

**Issue by s3phir0th** [richpeck/exception_handler#21]
Hello,
thanks for the great gem.

I was testing it in development environment (config.consider_all_requests_local  = false) under <b>Rails 4.2.5</b> and got an error when testing a RouteNotFound Exception that said:

```
Error during failsafe response: The controller-level `respond_to' feature has been extracted to the `responders` gem. Add it to your Gemfile to continue using this feature:
  gem 'responders', '~> 2.0'
Consult the Rails upgrade guide for details.
```
It seems respond_with got removed in Rails >4.2 and is used in exception_handler...
Like instructed I installed the responders gem (and ran rails g responders:install)
Then it was working. Maybe you should add responders to exception_handler's dependencies or in the installation instruction?

**Comment by richpeck** [comment]
Hey thanks for the feedback!!

This is interesting. I'll update the gem in the morning for you, we've always included responders by default - thanks for highlighting

**Comment by anthonypenner** [comment]
I had this issue as well. Installing the responders gem does fix it. Not a big deal.

**Comment by richpeck** [comment]
Thanks for the feedback - this dependency will be added with the next release
