### ISSUE TITLE
Using routes

### ISSUE THREAD

**Issue by tscritch** [richpeck/exception_handler#23]
Hello!
When my site fires a 400 error and renders within the application layout I get this error:
```
Completed 500 Internal Server Error in 212ms (ActiveRecord: 0.0ms)
Error during failsafe response: undefined local variable or method `root_path' for #<#<Class:0x007fd0c0409938>:0x007fd0c24946d0>
```
I have a _header.html.erb that uses the link_to tag with the root_path as the link. Is there a way around this? I also tried changing the default layout for 4xx errors but it still used my application layout.

Thanks for creating this awesome gem and thanks for the help!
-- Tad

**Comment by richpeck** [comment]
Hey Tad,

Thanks for taking the time -- the quickest fix *should* be to use `main_app.root_path`. Do you have a link to the repo I could look at? As you can imagine, catering for all setups can take time

R

**Comment by tscritch** [comment]
Ok sweet... So could I use this for all routes then? Just add main_app to the beginning of my routes?
What is it that makes that necessary?

And unfortunately no. I'm working on a site for a client and have my repo up on bitbucket for privacy. Really sorry cause I know how much it would help. However I can attach some code:

_header.html.erb:
```
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right" id="header-links">
          <li><%= link_to "Innovators", startups_path %></li>
          <li><%= link_to "Mentors", mentors_path %></li>
          <li><%= link_to "Investors", investors_path %></li>
          <li><a href="#">Blog</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About</a>
            <ul class="dropdown-menu">
              <li><%= link_to "Team", team_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Press", press_path %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
```

application.html.erb:
```
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>
```

application.rb: (I didn't need all the other variables)
```
config.exception_handler = {
	    db:   	false, #-> defaults to :errors if true, else use :table_name
	    email: 	false, #-> need to integrate

	    layouts: {
	      '400' => nil,
	      '500' => 'exception'
	    },
    }
```

**Comment by richpeck** [comment]
Unfortunately, you shouldn't use it for all routes; it's *meant* for use within an engine (like we have set up here).

The issue we have is that since `ExceptionHandler` uses the main "application" layout, it will expect any references to routes etc to be covered by the engine. 

Since we are using [`isolate_namespace`](http://guides.rubyonrails.org/engines.html#generating-an-engine), any routes are expected to be defined within the engine. The way around it is to prepend `main_app` to the route, allowing the engine to reference the routes of the main application.

We did include [`include Rails.application.routes.url_helpers`](https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exception_controller.rb#L15), which worked for us. 

---

The way to fix it is to make sure that any layout routes you use with `ExceptionHandler` are prepended with [`main_app`](http://edgeapi.rubyonrails.org/classes/Rails/Engine.html#class-Rails::Engine-label-Using+Engine-27s+routes+outside+Engine):

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right" id="header-links">
          <li><%= link_to "Innovators", main_app.startups_path %></li>
          <li><%= link_to "Mentors", main_app.mentors_path %></li>
          <li><%= link_to "Investors", main_app.investors_path %></li>
          <li><a href="#">Blog</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About</a>
            <ul class="dropdown-menu">
              <li><%= link_to "Team", main_app.team_path %></li>
              <li><%= link_to "Contact", main_app.contact_path %></li>
              <li><%= link_to "Press", main_app.press_path %></li>
            </ul>
          </li>
        </ul>
    </div>```

I know it's tedious, but it's *only* for the "main app" layouts used by the gem.

--

I'd also like to know what you mean when you said the gem wouldn't recognize that you'd changed the `400` layout?

Thanks for the prompt reply!

**Comment by tscritch** [comment]
Oh ok thank you so much for the links! I'm newer to rails and was unaware of engines! It all makes a lot more sense now.

As for the 400 layout I changed the layouts config to this: 
```
config.exception_handler = {
        db:     false, #-> defaults to :errors if true, else use :table_name
        email:  false, #-> need to integrate

        layouts: {
          '400' => 'exception',
          '500' => 'exception'
        },
    }
```
Then when my server gave a 400 it was still using 'layouts/application' as its layout. 

```
Processing by ExceptionHandler::ExceptionController#show as */*
  Rendered exception_handler/exception/show.html.erb within layouts/application (0.1ms)
```

Again thanks for all of your help!

**Comment by richpeck** [comment]
No problem, this is something I am going to have to test for the new version.

Have you tried the recommendation? The most important thing is to get it working

R

**Comment by tscritch** [comment]
Yup it's all working now!
![screen shot 2016-02-11 at 7 52 00 am 2](https://cloud.githubusercontent.com/assets/11529600/12981183/6c9d3754-d094-11e5-8bc2-b0857702b5f3.png)

Any suggestions for testing my 500 page though?

**Comment by richpeck** [comment]
Nice! Love the little face

> Any suggestions for testing my 500 page though?

Yeah that's simple - just make a loop in a view:

```
#app/views/x.html.erb
<% .each do |g| %>
<% end %>
```

This will give you a 500 error ;)

**Comment by tscritch** [comment]
Awesome! Thanks so much!
