### ISSUE TITLE
Gem size is 67M compressed!

### ISSUE THREAD

**Issue by midwire** [richpeck/exception_handler#24]
The size of the compressed .gem file is about 67M. That is unusually large for a gem, and even for a Rails engine gem.

It may be a good idea to get rid of the Photoshop files:

* readme/source/screen.psd - 49M
* readme/source/subtitle.psd - 59M
* readme/source/title.psd - 7.2M

I'll add a PR. Feel free to use it... or not. #25

**Comment by richpeck** [comment]
Hey buddy, thank you for pointing this out!!

I got rid of them all from the new version (0.5) which is going to be released at the end of the week. The files need to stay in the git repo, but I added `spec.files.reject!` to remove them from the gem itself.

https://github.com/richpeck/exception_handler/blob/0.5/exception_handler.gemspec#L20

**Comment by midwire** [comment]
Cool! I think that will make a difference. My current client doesn't want a 67M gem in production, but I think I can get it OK'd without those biggies.

Thanks for your work, nice gem!

**Comment by richpeck** [comment]
Thanks man, there's also a small problem with Rails 5 beta (`request.env` is deprecated, and there's another issue I forgot too). If you have any issues with it in the new version, post on here and I'll help you out.

No problem RE gem - we use it ourselves so invested some time to make it workable and flexible

R

**Comment by richpeck** [comment]
![untitledsdfsd](https://cloud.githubusercontent.com/assets/1104431/13437904/6ff4ea88-dfde-11e5-8ad8-f724fe70f142.png)

**Comment by midwire** [comment]
Sweet! Thanks again. I look forward to using it often.

**Comment by richpeck** [comment]
![untitledsdfsdf](https://cloud.githubusercontent.com/assets/1104431/13747695/6766f79a-e9f1-11e5-9dbc-420d424bd61b.png)
