### ISSUE TITLE
undefined local variable or method `info' for ExceptionHandler::Parser::Data:Class

### ISSUE THREAD

**Issue by jvhaperen** [richpeck/exception_handler#29]
Hi!

Just updated from 0.4.7 to 0.5.1 but there seems to be a bug in lib/exception_handler/parser/data.rb.
If my application throws an error, the exceptionhandler fails.

It tries to access the private "info" instance method from the class method "create". I see what you did in the change between 0.4.7 and 0.5.1, in the old version the initalize and save methods are instance methods that can access the info instance method. This code is moved to the new create class method but now "info" is unreachable.

**Comment by richpeck** [comment]
Hmm, this didn't show up in the testing. Tried to make EVERYTHING much more succinct this time around - do you have a screenshot of your error in the console I could look at? I've not had this issue so it will be good to see how its being caused

Thanks for sticking with the gem - some teething problems but they're getting sorted

**Comment by jvhaperen** [comment]
Sure!

![screen shot 2016-03-31 at 14 26 37](https://cloud.githubusercontent.com/assets/4244270/14175663/bda5333e-f74c-11e5-9f77-d336de1306e1.png)

ps. if I change the ExceptionHandler::Parser::Data class code locally from "def info" to "def self.info" the problem is fixed, but I'm not sure that is the desired/best change.

**Comment by richpeck** [comment]
Thank you for this, and for the prompt reply.

I'll look into it immediately - indeed, the issue would be a conflict between class/instance access to the data. Might be worth pushing a new ver of the gem to cover it as it's obviously a central problem.

Let me see the best way forward and will reply in a bit for you
