### ISSUE TITLE
It does not work for me.

### ISSUE THREAD

**Issue by wafendy** [richpeck/exception_handler#33]
Rails 4.2.6
ruby 2.3.0p0

I'm following the instructions:
- Installed gem 
- Added the config.exception_handler  in application.rb
- Execute rails generate exception_handler:views -v views controllers 

Is there anything else I need to do? This is far from plug and play.

**Comment by richpeck** [comment]
Hey buddy, Can you show you me your repo? It is plug and play -- try setting the `dev` option locally to see if it catches the exceptions:

![image](https://cloud.githubusercontent.com/assets/1104431/14780530/22573a34-0ad5-11e6-9bf9-66294abe3f7a.png)

**Comment by wafendy** [comment]
Hi Rich,

Thank you for your fast response. If I limit the config to only dev: true and remove the others then it's running fine.

**Comment by richpeck** [comment]
Thanks for the reply. Good to see it working -- do you have a screenshot of what you're trying to do so I can see what the issue is for you?

Thanks

Rich

**Comment by wafendy** [comment]
Hey Rich,

Does your gem work automatically in staging environment? Is there
additional configuration parameter that I have to set for staging and
production?

-wa

On Mon, Apr 25, 2016 at 11:55 PM, Richard Peck <notifications@github.com>
wrote:

> Thanks for the reply. Good to see it working -- do you have a screenshot
> of what you're trying to do so I can see what the issue is for you?
>
> Thanks
>
> Rich
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/richpeck/exception_handler/issues/33#issuecomment-214414361>
>



-- 
William Afendy

**Comment by wafendy** [comment]
Development is fine. Deployment to staging fails. I can deploy successfully if I remove gem.  Below is the full stack trace.

```
---- Begin output of cd /srv/www/my_app_staging/releases/20160427022532 && bundle exec rake assets:precompile RAILS_ENV=staging ----
STDOUT: 
STDERR: rake aborted!
NoMethodError: undefined method `protocol' for nil:NilClass
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/helpers/asset_url_helper.rb:227:in `compute_asset_host'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/helpers/asset_url_helper.rb:143:in `asset_path'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/actionview-4.2.5.2/lib/action_view/helpers/asset_url_helper.rb:162:in `asset_url'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/exception_handler-0.5.1/app/assets/stylesheets/exception_handler/error.css.erb:26:in `_evaluate_template'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:26:in `call'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/erb_processor.rb:13:in `call'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:23:in `block in call'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/utils.rb:183:in `dfs'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/bundle.rb:24:in `call'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:60:in `block in load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/loader.rb:44:in `load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `yield'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/cached_environment.rb:47:in `load'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/base.rb:66:in `find_asset'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:142:in `block in find'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:225:in `block in stat_tree'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:209:in `block in stat_directory'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:206:in `stat_directory'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/path_utils.rb:224:in `stat_tree'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `each'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:140:in `find'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:168:in `compile'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-rails-3.0.3/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-3.5.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/deploy/.bundler/my_app_staging/ruby/2.2.0/gems/sprockets-rails-3.0.3/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
```

**Comment by richpeck** [comment]
Hey man,

**Yes** it works in staging as well as prod/dev. I have it working in our staging env on Heroku right now:

![untitledsadfasd](https://cloud.githubusercontent.com/assets/1104431/14843884/8aa660b6-0c4b-11e6-9e8e-bf0c2ca3c00c.png)

I can explain more if you provide specifics.

---

Your error seems to be a precompile issue, specifically with line 25/26 of `error.css.erb`:

![untitledas](https://cloud.githubusercontent.com/assets/1104431/14843858/6b1a78c2-0c4b-11e6-9864-b3acf6e296c9.png)

I suspect the problem is *either* with your deploy pipeline (Capistrano?) or some of the backend settings.

Here are two references which may help:

 - http://stackoverflow.com/questions/28061460/rails4-template-error-in-mailer-in-production
 - https://github.com/gavinkflam/lightbox2-rails/issues/5

The issue seems to be the `asset_host` is either missing or inaccessible.

When we push to Heroku and our own cloud systems, we just use the `production` env details:

![untitledas](https://cloud.githubusercontent.com/assets/1104431/14844075/b100ac3e-0c4c-11e6-9736-021db387486f.png)

If you can confirm your setup, I can see about getting it working

R

**Comment by wafendy** [comment]
I use the generator to generate only the view and the controller as I do not need the assets. In my controller I render the existing public html files. Just want to keep it to the minimum.

```
  class ExceptionController < ApplicationController
    respond_to :html, :xml, :json

    helper ExceptionHandler::Engine.helpers      
    include Rails.application.routes.url_helpers 

    def show
      @exception = ExceptionHandler::Exception.new request 
      render file: Rails.public_path.join("#{@exception.status}.html"), status: @exception.status, layout: false
    end
  end
```

I'm deploying the app to Amazon EC2 using OpsWork.

**Comment by wafendy** [comment]
Come to think about it, I do not even need to generate the view, I just need a controller that will catch the exception at middleware level and render the public html files.

**Comment by richpeck** [comment]
Which public HTML files are you trying to render? Your own version of the views in `views/exception_handler/exception/show.html.erb`?

**Comment by richpeck** [comment]
Okay, so it seems you're trying to render `/app/views/[exception].html`... What layout are you using? If you get rid of the `exceptions` layout (which is HIGHLY RECOMMENDED for `500` errors), I think the assets will be okay without compilation.

If you invite me to your repo, I can make some suggestions on the code?

**Comment by wryanp** [comment]
Hi everyone.  This is still happening to me with Rails 6 and an S3 asset host.  I'm using version 0.8.0.0 of exception_handler.  I am not overriding any views besides the layout.

**Comment by wryanp** [comment]
This is the message I get on RAILS_ENV=production rake assets:precompile:

`NoMethodError: undefined method `protocol' for nil:NilClass
       /tmp/build_9947e61d_/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.2/lib/action_view/helpers/asset_url_helper.rb:301:in `compute_asset_host'
       /tmp/build_9947e61d_/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.2/lib/action_view/helpers/asset_url_helper.rb:210:in `asset_path'
       /tmp/build_9947e61d_/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.2/lib/action_view/helpers/asset_url_helper.rb:229:in `asset_url'
       /tmp/build_9947e61d_/vendor/bundle/ruby/2.7.0/gems/exception_handler-0.8.0.0/app/assets/stylesheets/styles/_exception.css.erb:27:in `call'`
