### ISSUE TITLE
Is there anyway to stop handling 40* errors altogether? 

### ISSUE THREAD

**Issue by csteez** [richpeck/exception_handler#35]
I'm working on an existing rails app, and in many cases we return json with custom error messages for 404s. I added this gem to handle 500s, but since it catches 404s as well, we're running into some unintended side effects. I tried returning json in the case of 404, but it doesn't have the original text and I'm concerned api users might be dependent on the error text. 

There are too many of these situations to handle it in the ExceptionHandler controller. 

Any suggestions?

**Comment by richpeck** [comment]
Hi Christina,

Currently there is no "pre-baked" way to prevent the `40x` errors from being caught. I am working on a big upgrade and will be adding custom error handling etc to the system.

The workaround (for now) will be to prevent the errors being processed at controller level (which will allow you to send the 404 JSON response without EH getting in the way):

rails generate exception_handler:views -v controllers

```
# app/controllers/exception_handler/exception_controller.rb
...
def show
  @exception = ExceptionHandler::Exception.new request #-> Service Object
  
   return if /^(4[0-9]{2})$/ !~ @exception.code.to_s #-> should exit loop, although I think it will still catch the error at the middleware level. 

  render status: @exception.status #-> Show apppropriate response
end
```

TBH I don't know if the above will work as it will still catch the error in the middleware. If it doesn't, I'll add some of the changes I have been meaning to implement to see if we can get it working

**Comment by csteez** [comment]
So I tried that, and it actually still returns a 500 error instead of a 404. When I tried what you posted, it actually evaluated to false for that if (despite @exception.code.to_s being '404'). I tried updating it to just match on 404 and when I did so, it actually continued to show the error it was showing before (can't find a view that returns json). Do you have any other suggestions?

I'm pretty green with RoR so I'm pretty out of my depths on figuring out the right way to handle this.

**Comment by richpeck** [comment]
Thanks for the update - **do you have a link to a public repo I could look at**? 

The whole JSON response thing is throwing me - it's good that you've done it that way, but I need to know how it works specifically before making another suggestion

**Comment by csteez** [comment]
Unfortunately, our code is in a private github repo so I'm afraid I can't share it. I'm not 100% sure on what actually returns the 404 json - it seems like probably some middleware? In some cases we're raising 404's and other status codes with custom exception messages and in others it's a generic error message (like {"status":"404","error":"Not Found"}). 

I ended up adding a conditional to check if json was requested, and if so, return the status code and message as json. Allegedly this won't break our users, but I guess I'll find out. 

I really appreciate your swift replies!
