### ISSUE TITLE
Trouble Installing on Heroku

### ISSUE THREAD

**Issue by kmurray8204** [richpeck/exception_handler#38]
I included gem 'exception_handler', '~> 0.6.5' in my Gemfile and ran a bundle install.  I do not see any of the assets (exception controller, defaults views, etc.) in my project and exceptions are not being handled by Exception Handler.  I am using Rails 5 and developing in Heroku.  What am I doing wrong?

**Comment by richpeck** [comment]
Can you show me the link to your Heroku app?

--

The assets shouldn't be in the app anyway - the gem should have them stored in its own files. If you give me more details - like your heroku app or the console log of a `rake assets:precompile`, I will be in a better position to help. We have it working 100% in Heroku with Rails 5

**Comment by kmurray8204** [comment]
My production app has stopped working since implementing the Exception Handler Gem.  I am in the process of troubleshooting with Heroku now.  This is their most recent response:

Hi there,

This looks like you have some kind of syntax error in one of your config files. Are you able to run bundle exec puma -C config/puma.rb locally without this error?

Let me know if you have any further questions.

**Comment by richpeck** [comment]
This shouldn't happen - do you have a link to the production app? Can you add me as a contributor? 

![untitled-1](https://cloud.githubusercontent.com/assets/1104431/21569416/8e6aec54-ceb4-11e6-8a36-138443aa227e.jpg)

**Comment by kmurray8204** [comment]
I added you as a collaborator.  URL for Production App is https://red-hockey-58751.herokuapp.com/

**Comment by richpeck** [comment]
https://dashboard.heroku.com/apps/red-hockey-58751/logs

![untitled-1f](https://cloud.githubusercontent.com/assets/1104431/21569577/e9015d46-ceb5-11e6-95c9-21f65208f71b.jpg)

You need to add the `responders` gem to your `Gemfile` (which *should* be done automatically):

```
# Gemfile 
gem 'responders', '~> 2.3'
```

**Comment by kmurray8204** [comment]
OK let me try that

**Comment by kmurray8204** [comment]
IT WORKED!  Thank you so much for your quick response!

**Comment by richpeck** [comment]
No problem :)

You should update your v of Rails to the latest (`5.0.1`) and you should also look at using a later version of ruby (`2.4.0` was released on Christmas day).

If you need any further help, please just ask!
