### ISSUE TITLE
NameError: uninitialized constant CreateErrors

### ISSUE THREAD

**Issue by lethunder** [richpeck/exception_handler#45]
Hello everyone,
i have an error when running rake db:migrate after generating migration file.

My migration file looks like this

    create_table :false do |t|
      t.references  :usable, polymorphic: true
      t.text        :class_name
      t.text        :message
      t.text        :trace
      t.text        :target_url
      t.text        :referer_url
      t.text        :params
      t.text        :user_agent
      t.timestamps
    end

This is the error
NameError: uninitialized constant CreateErrors

Thanks in advance for your help

**Comment by richpeck** [comment]
Thanks for the report, are you using the latest version?

**Comment by lethunder** [comment]
hello i'm using exception_handler (0.5.1) with rails 4.1.8 and ruby 2.0.0

**Comment by richpeck** [comment]
If you update to the latest version (`0.7.5`), you'll be able to run the migration without putting the migration file in your app. As long as `db` has a value in the config, you'll be able to run `rails db:migrate` and it will pull the file from the gem. If you use a different table name to the standard, it will infer that from the config:

```
# config/application.rb
config.exception_handler = {
  db: "TEST" #=> will create "TEST" db in migration
}

```
If you give me a repo name, I can take a look if you want

**Comment by lethunder** [comment]
i'm now on my comuter with a windows 10 and ruby 2.2.4 with rails 5.0.1.
But i can't generate migration even with exception_bandler 0.7.5.15

Could not find generator 'exception_handler:migration'. Maybe you meant 'exception_handler:views', 'active_record:migration' or 'test_unit:integration'
Run `rails generate --help` for more options.

Any idea?

**Comment by richpeck** [comment]
You don't need to generate the migration - you just need to run `rails db:migrate` and it will include the exception handler migration in your app!

It's an experiment - works okay for us - https://github.com/richpeck/exception_handler#migrations-deprecated

**Comment by lethunder** [comment]
Thanks richpeck it works nicely. Very good job
