### ISSUE TITLE
Need to rewrite repo without huge files

### ISSUE THREAD

**Issue by Startouf** [richpeck/exception_handler#48]
Issue https://github.com/richpeck/exception_handler/issues/41 was not addressed
The repository needs to be rewritten to exclude big files (or at least use git-lfs)

Currently this project is very hard to maintain, only cloning the repo took 30 minutes for me (speed limited by github, not my network) and I don't even want to consider adding this to a production environment.

Please avoid committing big files directly. You can have a look at https://rtyley.github.io/bfg-repo-cleaner/ or https://help.github.com/articles/removing-sensitive-data-from-a-repository/ to clean the mess.

The repo is 1.2 GB

**Comment by richpeck** [comment]
The gem ignores the files, I kept them in the repo to keep them in a central location. Will look at removing them to help with development

**Comment by Startouf** [comment]
When doing development and trying out non-released gems, `bundle` will still download the git repository. Therefore people are unable to use their own fork without republishing a new version or rewriting the repository to remove such files.

**Comment by richpeck** [comment]
Certainly, I forgot about that. I didn't realize people were using it from source. I'll get rid of the PSD files, pretty stupid to keep them in tbh.

**Comment by richpeck** [comment]
Ridded the master branch of the PSD's

**Comment by richpeck** [comment]
Still 500mb, will ask Github about how to remove historic objects because that's a ridiculous size. Thanks for pointing the problem out
