### ISSUE TITLE
Error when running  rails generate exception_handler:install

### ISSUE THREAD

**Issue by cmendla** [richpeck/exception_handler#56]
I got the following error when trying to run  rails generate exception_handler:install based on 

http://www.rubydoc.info/gems/exception_handler/0.3.45

I realize that is an old doc. I am just trying to set things up so the config files are available

```
 chris@chris-VirtualBox:~/Documents/RailsProjects/LineIndex$ rails generate exception_handler:install
 Running via Spring preloader in process 30401
 Expected string default value for '--serializer'; got true (boolean)
 Could not find generator 'exception_handler:install'. Maybe you meant 'exception_handler:views', 'responders:install' or 'integration_test'
 Run `rails generate --help` for more options.
```
Running ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Rails 5.0.2

bundle info gives

```
chris@chris-VirtualBox:~/Documents/RailsProjects/LineIndex$ bundle info exception_handler
  * exception_handler (0.7.7.0)
	Summary: Rails gem to show custom error pages in production. Also logs errors in db & sends notification emails
	Homepage: https://github.com/richpeck/exception_handler
	Path: /home/chris/.rvm/gems/ruby-2.4.1/gems/exception_handler-0.7.7.0
```

**Comment by richpeck** [comment]
Hi Chris, let met have a look at this for you

**Comment by richpeck** [comment]
Ok, so the problem here is that `exception_handler:install` generator doesn't exist any more.

I suppose this should have been more specific in the Readme (which I'm working on), but nonetheless it doesn't exist in `0.7.7.0` (current version). At present, if you just want to use the gem to catch errors - it does this out of the box. You will just need to add `dev: true` to the `config` file of your app (as follows):

```
# config/application.rb
config.exception_handler = { dev: true }
```

This will allow you to see the custom error pages in development mode.

If you wish to change the controller or any of the views, that's when you'd want to use the `exception_handler:views` generator:

```
rails g exception_handler:views
rails g exception_handler:views -v views
rails g exception_handler:views -v controllers
rails g exception_handler:views -v models
rails g exception_handler:views -v assets
rails g exception_handler:views -v views controllers models assets 
```
If you could let me know specifically what you were hoping to do with the generator, I'll be able to provide you with details on how to achieve it.

**Comment by cmendla** [comment]
Rich - OK, I'll try it 'out of the box' and see how that works. 

One thing I want to do is to send an email to the admin team when an exception is encountered. From what I see, I think the gem will do that. 

I probably won't get back to this until later in the weekend. 

Thanks again for the amazingly quick response!!!

**Comment by richpeck** [comment]
No problem, please just ask here if you need more help.

**Comment by dgreen22** [comment]
Rich - absolutely love the gem but I'm so confused by the documentation.  Your explanation above did way more for me than everything else.  Just food for thought from a N00B.

**Comment by richpeck** [comment]
Hey bud, no problem.

Reworking the README right now - it will be much more detailed than it is now  - thanks for the feedback :)

**Comment by daluzguilherme** [comment]
@richpeck , I tried to put the code 
`config.exception_handler = { dev: true }` 
into my /config/application.rb but nothing happens. Am I wrong on where to paste that code?

My code is as follows:
```
module SIGS
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 5.1

    #config/application.rb
    config.exception_handler = { dev: true }

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.
  end
end
```

**Comment by richpeck** [comment]
1. Have you loaded the gem in the gem file?
2. You're running inside a module - is this a naked app or embedded in something else?

**Comment by daluzguilherme** [comment]
Yes, I haver loaded It in the gemfile.
Thats a naked app

Em 23 de abr de 2018 3:49 AM, Richard Peck <notifications@github.com> escreveu:

  1.  Have you loaded the gem in the gem file?
  2.  You're running inside a module - is this a naked app or embedded in something else?

**Comment by richpeck** [comment]
Is there anyway I could look at the repo? Many thanks for the replies so far.

**Comment by daluzguilherme** [comment]
Sure, here it is: https://github.com/daluzguilherme/SIGS-GCES

**Comment by richpeck** [comment]
Thanks, can't seem to find the `exception_handler` gem in the Gemfile: https://github.com/daluzguilherme/SIGS-GCES/blob/master/SIGS/Gemfile

**Comment by richpeck** [comment]
Great to hear! Thanks for using the gem
