### ISSUE TITLE
Migration fails with: NoMethodError: undefined method `[]' for ActiveRecord::Migration...

### ISSUE THREAD

**Issue by whatch** [richpeck/exception_handler#58]
After enabling the db option in app...config, then running migrations, I was receiving this error:

> NoMethodError: undefined method `[]' for #<ActiveRecord::Migration: ...

Not sure, but I think your migration relies on rails5, (I'm on 4.x). I worked around it by disabling db in config, which you have to in order to generate the migration by hand (would get a migration pending exception otherwise), then determining what the proper migration would be by looking at the code. Included here in case somebody else hits this. 

```
class CreateErrors < ActiveRecord::Migration
  def change
    create_table :errors do |t|
      t.string :class_name
      t.string :status
      t.text :message
      t.text :trace
      t.string :target
      t.string :referrer
      t.text :params
      t.string :user_agent
      t.timestamps
    end
  end
end
```

**Comment by whatch** [comment]
Ohhh, just hit a major problem with my above work around, via manually running the migration, which baffles me. The current solution works, and then I toggle db:true in config, and then everything behaves as expected. But, if I add another migration (unrelated to errors table) and attempt to run it, I get a duplicate named migration error, and the migration fails. 

> rake aborted!
> ActiveRecord::DuplicateMigrationNameError: 
> 
> Multiple migrations have the name CreateErrors

If I toggle db:false, the migration will succeed. So, I'm missing the entry that you're looking for when determining if there's other migrations, and it happens that mine is titled "CreateErrors" as well. Why isn't it picking up on the existence of the errors table, and instead looking for the migration name? Why does it even think it needs to migrate, is the appropriate question I suppose?

I renamed the existing migration file and classname, leaving the table name as :errors, then rolled back data in the schema_migrations table, and updated schema.rb with rake db:schema:dump, so as to start clean. Leaving the config db:true, I attempted to migrate again, and this time, back to the original error. Toggling to db:false, the migration succeeds, but next time I run a migration, I'm once again back to this gem attempting to run it's own migration. This is a serious flaw, as it will completely break the automated deployment. I think a generator for the migration would avoid all this, but there must be some means of fixing this as is.

**Comment by whatch** [comment]
Ah, found the problem: I had the latest version, 7.xx, as I'd only done: gem 'exception_handler' in my gemfile. Reading through your wiki under Database, I found:

`gem  'exception_handler', '~> 0.6.5'`

That might be better placed in the readme more prominently.  But hey, it's working now;-)

**Comment by richpeck** [comment]
I will be updating the readme in the next two weeks or so - thanks for point this out so thoroughly
