### ISSUE TITLE
Using with active admin?

### ISSUE THREAD

**Issue by whatch** [richpeck/exception_handler#59]
I've been trying to add an activeadmin resource for the model you're using, but no luck. Has anybody done this?

**Comment by richpeck** [comment]
Can you share your code?

**Comment by whatch** [comment]
```
ActiveAdmin.register Error do

  menu :if => proc{ current_user.admin?}

end
```

The issue I'm having is I don't know how to refer to your model class in the ActiveAdmin.register call. I've also tried adding it's module, etc, and nothing works. So, the question is, how do I refer to the model so it'll work with active admin?

**Comment by whatch** [comment]
And of course, no sooner than I sent that, then discovered the proper module and name, being ExceptionHandler::Exception, and now it's working. Closing... ;-)
