### ISSUE TITLE
mail configuration

### ISSUE THREAD

**Issue by simonini** [richpeck/exception_handler#6]
In config file there is 

config.email

but if i activated i get this error

undefined method `email='

**Comment by nlyczak** [comment]
Hi Rich, 

Installed your gem today with Rails 5.  It worked incredibly well.  Thank you so much!

I would love to use the email notification feature.
After I set  **email: true**, what else do I need to do?  
Are there further instructions somewhere?

Thank you!

**Comment by richpeck** [comment]
Hi @nlyczak unfortunately this is not in the system yet - I have a new version slated for release soon that will include it for sure.

**Comment by richpeck** [comment]
Email has been included in 0.6.5, more instructions on the way.
