### ISSUE TITLE
Specify app directory where exception_handler picks up custom views

### ISSUE THREAD

**Issue by MadPositron** [richpeck/exception_handler#61]
First of all, thank you for this gem + the detailed article on using middle-ware level exception handling. Your work is very much appreciated.

Our rails project is heavily engine/component based so there is no root app directory (more like /engines/X/app/, /engines/Y/app etc.. 

We had trouble to get it working by including it within the engines, so it has been included it in the root folders Gemfile.

One issue with using root was that ExceptionHandler assumes a ::ApplicationController exists (engines do namespace X::ApplicationController) but this can be worked around by re-defining ::ApplicationController. 

Second issue is that if views are missing in root/app/views/ it automatically picks up the gem's default views. So generating custom views/layouts in the root app dir works but i'd rather place them into the engines app dir. As a side note: Rails picks up overrides automatically in the order of mounting if placed in the engines app dir but this happens only for mounted engines.

Q: Is there a config option to override the asset/views path so it picks up my views folder first instead of root views folder or default views from the gem. Alternatively is there a way or example of how to run it from an engine which has been mounted ?

(Worst case we'd need to create an app folder in root, which would be containing only exception_handler code).

**Comment by MadPositron** [comment]
After some trial and error, the solution to this is to specifically override the exception_handler controller in your engine by using the generator. The exception_handler-controller will pick up the engines ApplicationController properly as well. Maybe drop a line in the README on how to do this:

- `require 'exception_handler'` in your engines `lib/engine_name.rb`
- generate view and controller in your engines app folder using the generator
- mod your Rails.application.config as stated in either initializer/application.rb or engine.rb

**Comment by richpeck** [comment]
Hey sorry about the lack of reply - Github didn't send the original request to my email. I am currently revamping the README so will include this

**Comment by MadPositron** [comment]
No worries,
another note: when using this method in production embedding exception_handler in engines, namespace the application controller properly `ExceptionsController < MyEngineName::ApplicationController`. Funnywise not namespacing it works in dev but once deployed rails is picky about it.
