### ISSUE TITLE
Send exception full trace in email

### ISSUE THREAD

**Issue by omairrazam** [richpeck/exception_handler#75]
How can i also send full details of error in email so that I could figure out where it actually happened? rather than just seeing the error description?

**Comment by richpeck** [comment]
The mailer uses the [`@exception`](https://github.com/richpeck/exception_handler/blob/master/app/controllers/exception_handler/exceptions_controller.rb#L20) object which contains all the stack trace etc:

```
#/app/views/exception_handler/mailers/new_exception.erb
<h1><%= Rails.application.class.parent_name %> (<%= Rails.env.titleize %>)</h1>

<strong><u><%= @exception.response %> (<%= @exception.status %>)</u></strong>
<p><%= @exception.message %></p>
```

If you wanted the full stack trace, you'll want to re-create the above mailer in your app and use the [`@exception.trace`](https://github.com/richpeck/exception_handler/blob/master/app/models/exception_handler/exception.rb#L143) object.
