### ISSUE TITLE
Send current user details with email.

### ISSUE THREAD

**Issue by kickbk** [richpeck/exception_handler#76]
Is there a way to send details of the current_user (I'm using devise) along with the error notification email?

**Comment by richpeck** [comment]
This used to be included in the gem, but a number of people had issues with it, so it was removed.

I can work on including it again if you want?

**Comment by kickbk** [comment]
Yes please, would appreciate it, or just instructions on how to add it would be enough if it's something we can add in an initializer or by extending the functionality somehow. Thanks!
