### ISSUE TITLE
whats the deal with usable?

### ISSUE THREAD

**Issue by fwidtmann** [richpeck/exception_handler#9]
hi,

what should we do with usable_type and usable_id in db? 

error.rb
<pre>
belongs_to :usable, polymorphic: true
</pre>

is there any documenation?

**Comment by richpeck** [comment]
Sorry about this, and the lack of reply.

The `usable` attributes are meant to record any logged-in users. 

As you can see from https://github.com/richpeck/exception_handler/blob/master/lib/exception_handler/parser.rb#L59, the `parser` looks for any logged-in users (currently using Devise only):

			if user
				info[:usable_type] 	= user[:type]
				info[:usable_id] 	= user[:id]
			end

The aim, although not implemented anywhere near well enough, is to give the admin an idea as to which user raised the exceptions. Working on getting this fixed.
